# sudo necessary for addons
sudo: required
dist: trusty

language: java

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java9-installer

install: ./gradlew clean jar
script: ./gradlew check

env:
  global:
    - JAVA_9_HOME=$(jdk_switcher home oraclejdk9)
    - BINTRAY_USER=alicederyn
    - BINTRAY_ORG=inferred
      # BINTRAY_KEY
    - secure: "Ci4GciF9lPGiR9GcJAoNcBE/nXuCXBzwUTvWB48r5p5Zuc+W7gRr6oP/l625Of/Du5kNLpyCBywD/lOX9VEMY51yHqE+2YFAg6yZ0pIRcrUxLA8YHDWXtbdzF/UvUMHqGkohQv1Tww/5Tookh8jAI/BUgVM2kTbK5t68GDlrpQU="

deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload --stacktrace --info
  on:
    tags: true
